---
- name: Install repository Webtatic
  package:
    name: "{{ item }}"
    state: "{{ wtd_repo_webtatic_state }}"
  with_items:
    - "{{ wtd_repo_webtatic_packages }}"
  when: wtd_repo_webtatic_enabled
