---
- name: Install repository Webtatic 
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ wtd_repo_webtatic_packages }}"
  when: wtd_repo_webtatic_enabled

- name: Include cleanup tasks
  include_tasks: cleanup.yml
  when: not wtd_repo_webtatic_enabled
